"""Single-path effective value, contributing sources and ordered assignment history."""

from __future__ import annotations

import json
from collections.abc import Callable
from typing import Any

import yaml

from helm_valuetrace.models import PathKey, TraceResult, path_text
from helm_valuetrace.output.safety import contributor_rows, escaped_path, terminal_safe


def format_explain(
    key: str,
    path: PathKey,
    result: TraceResult,
    redactor: Callable[[Any, PathKey], Any],
    output_format: str = "text",
) -> str:
    from helm_valuetrace.core import MISSING, _lookup, final_assignment

    history = result.history
    if hasattr(history, "related_events"):
        related = history.related_events(path)
    else:
        related = [(path, a) for a in history.get(path, [])]
    final = final_assignment(path, history)
    value = _lookup(result.values, path)
    present = value is not MISSING
    contributors = contributor_rows(path, history)
    mixed = len({c["file"] for c in contributors}) > 1
    active_ids = {id(a) for items in getattr(history, "contributors", {}).values() for a in items}
    reason = (
        "The value is absent after parent replacement or Helm null coalescing."
        if not present
        else "The container combines the surviving assignments listed under contributing sources."
        if mixed
        else "Chart defaults supplied this value after user layers were merged."
        if final and final.source_type.value == "default"
        else "The last surviving assignment wins after files, flag groups, and default coalescing."
    )
    doc = {
        "key": key,
        "path": list(path),
        "escaped_key": escaped_path(path),
        "present": present,
        "final_value": redactor(value, path) if present else None,
        "final_source": "multiple sources" if mixed else final.location if final else None,
        "contributors": contributors,
        "generated": path in getattr(history, "generated", {}),
        "history": [
            {
                "key": path_text(p),
                "path": list(p),
                "source": a.location,
                "source_type": a.source_type.value,
                "file": a.source,
                "line": a.line,
                "column": a.column,
                "status": "contributing" if id(a) in active_ids else "overridden",
                "value": redactor(redactor(a.value, p), path),
            }
            for p, a in related
        ],
        "reason": reason,
    }
    if output_format == "json":
        return json.dumps(doc, indent=2, ensure_ascii=True, allow_nan=False)
    if output_format == "yaml":
        return yaml.safe_dump(doc, sort_keys=False, allow_unicode=False).rstrip()
    lines = [
        terminal_safe(key),
        "",
        "Final value:",
        "  " + (_fmt_val(doc["final_value"]) if present else "<absent>"),
        "",
        "Source history:",
    ]
    if not doc["history"]:
        lines.append("  No explicit assignment at this path.")
    for item in doc["history"]:
        lines.append(
            f"  {terminal_safe(item['source'])}: {_fmt_val(item['value'])} "
            f"({item['source_type']}, {item['status']}; {terminal_safe(item['key'])})"
        )
    if doc["final_source"]:
        lines.extend(["", "Contributing sources:" if mixed else "Final winner:"])
        lines.extend("  " + terminal_safe(c["source"]) for c in contributors)
        if not contributors:
            lines.append("  " + terminal_safe(doc["final_source"]))
    if doc["generated"]:
        lines.append("  This null slot was generated by indexed list expansion.")
    lines.extend(["", reason])
    return "\n".join(lines)


def _fmt_val(value: Any) -> str:
    if isinstance(value, str):
        return terminal_safe(value)
    return json.dumps(value, ensure_ascii=True, allow_nan=False, separators=(",", ":"))
